### ISSUE TITLE
Allow `nolink` or `none` empty URLs

### ISSUE THREAD

**Issue by froboy** [ynorth-projects/openy_repeat#20]
Drupal [allows empty links](https://www.drupal.org/project/drupal/issues/2698057) to be made with `<nolink>` or `<none>` in the link field URI text. We should handle this, otherwise the url appears as `href="route:<nolink>"`.

**Comment by shelleygoetz** [comment]
Jira ticket created @froboy https://openy.atlassian.net/browse/MAINTAIN-259
