### ISSUE TITLE
Memory consumption is high

### ISSUE THREAD

**Issue by AndreyMaximov** [ynorth-projects/openy_repeat#32]
When the openy_repeat paragraphs are loading for the first time, the `OpenyRepeatRepository::getLocations()` method tends to get most session nodes loaded. This makes the entity memory cache service consume quite some memory, in our case, more than 256 MB.

See https://github.com/ynorth-projects/openy_repeat/blob/928a661ee6a8599d94781c5c7f0215c7800362de/src/OpenyRepeatRepository.php#L122

**Comment by podarok** [comment]
Thanks
